"""Generate deterministic contract artifacts that must be committed."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from mini_fde.contracts.base import CONTRACT_VERSION  # noqa: E402
from mini_fde.contracts.corpus import CorpusManifest  # noqa: E402
from mini_fde.contracts.events import PUBLIC_EVENT_ADAPTER  # noqa: E402
from mini_fde.contracts.openapi import build_openapi_document  # noqa: E402
from mini_fde.contracts.report import CanonicalReport  # noqa: E402


def _json(document: Any) -> str:
    return json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _typescript_placeholder() -> str:
    return f"""// Generated by scripts/generate_contract_artifacts.py; do not edit.
// Phase 1 has no executable BFF API, so this is deliberately a narrow contract artifact.

export const CONTRACT_VERSION = '{CONTRACT_VERSION}' as const;

export type ContractVersion = typeof CONTRACT_VERSION;

export interface ContractArtifactIndex {{
  readonly canonicalReportSchema: 'contracts/report-schema/canonical-report.schema.json';
  readonly corpusSchema: 'contracts/corpus-schema/corpus-manifest.schema.json';
  readonly publicEventSchema: 'contracts/event-schema/public-event.schema.json';
  readonly openApi: 'contracts/openapi/local-contracts.openapi.json';
}}
"""


def expected_artifacts() -> dict[Path, str]:
    manifest = {
        "contract_version": CONTRACT_VERSION,
        "artifacts": {
            "canonical_report": "contracts/report-schema/canonical-report.schema.json",
            "corpus_manifest": "contracts/corpus-schema/corpus-manifest.schema.json",
            "public_event": "contracts/event-schema/public-event.schema.json",
            "openapi": "contracts/openapi/local-contracts.openapi.json",
            "typescript_placeholder": "packages/frontend-contracts/src/generated.ts",
        },
        "scope": "local-provider-neutral-foundation",
    }
    return {
        ROOT / "contracts/report-schema/canonical-report.schema.json": _json(
            CanonicalReport.model_json_schema()
        ),
        ROOT / "contracts/corpus-schema/corpus-manifest.schema.json": _json(
            CorpusManifest.model_json_schema()
        ),
        ROOT / "contracts/event-schema/public-event.schema.json": _json(
            PUBLIC_EVENT_ADAPTER.json_schema()
        ),
        ROOT / "contracts/openapi/local-contracts.openapi.json": _json(build_openapi_document()),
        ROOT / "contracts/contract-version-manifest.json": _json(manifest),
        ROOT / "packages/frontend-contracts/src/generated.ts": _typescript_placeholder(),
    }


def generate(check: bool = False) -> bool:
    """Write artifacts, or report whether checked-in artifacts have drifted."""

    expected = expected_artifacts()
    drifted = [
        path
        for path, content in expected.items()
        if not path.is_file() or path.read_text() != content
    ]
    if check:
        if drifted:
            relative_paths = ", ".join(str(path.relative_to(ROOT)) for path in drifted)
            print(f"Generated contract artifacts are stale: {relative_paths}", file=sys.stderr)
            return False
        return True
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return 0 if generate(check=args.check) else 1


if __name__ == "__main__":
    raise SystemExit(main())
