// Generated by scripts/generate_contract_artifacts.py; do not edit.
// Phase 1 has no executable BFF API, so this is deliberately a narrow contract artifact.

export const CONTRACT_VERSION = '1.0' as const;

export type ContractVersion = typeof CONTRACT_VERSION;

export interface ContractArtifactIndex {
  readonly canonicalReportSchema: 'contracts/report-schema/canonical-report.schema.json';
  readonly corpusSchema: 'contracts/corpus-schema/corpus-manifest.schema.json';
  readonly publicEventSchema: 'contracts/event-schema/public-event.schema.json';
  readonly openApi: 'contracts/openapi/local-contracts.openapi.json';
}
